### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by waylaidwanderer** [0xFireball/PenguinUpload#10]
What does the rest of the site look like?

**Comment by 0xFireball** [comment]
Hello! I can send you some screenshots from a temporary instance if you like.

I'm glad to see interest!

**Comment by 0xFireball** [comment]
Login screen:
![image](https://cloud.githubusercontent.com/assets/15932100/21915069/45a958ba-d8ec-11e6-86e4-f8b079b98695.png)

Upload screen:
![image](https://cloud.githubusercontent.com/assets/15932100/21915114/94781936-d8ec-11e6-8b6c-388f702bdb8d.png)

Upload screen with some files:

![image](https://cloud.githubusercontent.com/assets/15932100/21915125/aa4f1e76-d8ec-11e6-824f-199a77987688.png)

Files screen:

![image](https://cloud.githubusercontent.com/assets/15932100/21915132/af929be2-d8ec-11e6-990a-3a8d5b8a5fcd.png)

Navigation:

![image](https://cloud.githubusercontent.com/assets/15932100/21915136/b5fdba20-d8ec-11e6-81a7-22ef705f852c.png)

Account page:

![image](https://cloud.githubusercontent.com/assets/15932100/21915145/bef83948-d8ec-11e6-9c5c-45479783a88f.png)


The rest of the account page:

![image](https://cloud.githubusercontent.com/assets/15932100/21915152/c44e08a0-d8ec-11e6-863d-64ce35437fc1.png)


Password protecting a file:

![image](https://cloud.githubusercontent.com/assets/15932100/21915162/ced066e2-d8ec-11e6-86cf-572dfe256fa1.png)

Downloading a file:

![image](https://cloud.githubusercontent.com/assets/15932100/21915171/e198a38e-d8ec-11e6-8e2a-060ee4e9192e.png)

This should cover most of the application. Let me know if you need anything else!

**Comment by 0xFireball** [comment]
If you like, you can also tweak the UI colors and theming by editing the material palette colors:
https://github.com/0xFireball/PenguinUpload/blob/master/PenguinUpload/src/PenguinUpload/ClientApp/main.js#L38-L49

**Comment by waylaidwanderer** [comment]
Looks good! Will there be an option for linking directly to the files? (e.g. `http://example.com/uploads/file.ext`) I could use an FTP server but I like this web interface.

**Comment by 0xFireball** [comment]
Yes, there is an API that provides full and direct access to files. In fact, there is an API route for everything that can be done through the web interface.

Files can be directly downloaded with a direct link using the route `/api/download/{fileId}`, where you replace `fileId` with the file GUID. This can be retrieved by looking at the URL or using the API. For password protected files, you specify the password like this: `/api/download/{fileId}!{password}` (an `!` separates the ID and the password)

You can also upload files directly through the API. The API will return some metadata about the file, including its ID when you do this.

**Comment by waylaidwanderer** [comment]
Instead of having the GUID in the link though, I'd like it to have it be a direct link to the file. Basically I'd use this to upload images and videos which you can paste in a chat like Discord which would show a preview directly.

If it's not an option I can always fork it :P

**Comment by 0xFireball** [comment]
Yes, using the GUID in the link gives you a direct link to the file. If you link to `https://my-server.com/api/download/{fileId}`, the link will directly download the file without any download page. This would fit your use case.

**Comment by 0xFireball** [comment]
If you want an easy way to get the GUID/direct link for a file, just visit the download page, with file URLs that look like: `https://server.xyz/#/d/83f26ea8-bbaf-4ecf-99cb-43a7ba31b892`. Then replace the `#/d` with `/api/download`, and *bam*, you have a direct link.

**Comment by waylaidwanderer** [comment]
I mean I'd like to be able to download the file in the format above, with the file name for clarity.

**Comment by 0xFireball** [comment]
If you think about it, the reason the file name isn't part of the URL is because of possible collisions. GUIDs are far, far less likely to collide, and this is why GUIDs are used in the URL. Using file names instead of GUIDs would not work for most users of the application, as it is designed to allow many different user accounts to each upload their own files.

Is this a satisfactory answer?

**Comment by 0xFireball** [comment]
If I understand you correctly, the download API works for you, but you want to be able to share with the file name instead of a GUID?

**Comment by waylaidwanderer** [comment]
I get it, but yeah that's what I want. Maybe my use case isn't the best fit for this app.

**Comment by 0xFireball** [comment]
Please let me know if you have any other questions or concerns. I am closing this issue as it seems to be resolved.
