### ISSUE TITLE
I can't seem to compile properly

### ISSUE THREAD

**Issue by ExodusTime** [0xFireball/PenguinUpload#24]
I've been trying to compile the build, everything seems to be fine but i cant find any .html file inside any folder

i'm not sure if this is normal result of the build but these are the files built

![](https://yourgi.ga/taZ/adRNX.png)

![](https://yourgi.ga/Dc7/adRNY.png)

![](https://yourgi.ga/mIw/adRNZ.png)

More than an issue im in need of help because i suck building stuff :P :<
Thanks for the help @0xFireball

**Comment by 0xFireball** [comment]
Hi @ExodusTime,
I'm glad to see interest in this project!
Regarding the build, everything looks right; this is the compiled output from the app. In fact the compiled client application is in `Views/`, but to actually host the server, you need to run the server application, which you can do like this:

`dotnet PenguinUpload.dll`

That will use the `dotnet` runtime to run PenguinUpload on .NET Core.
Be sure to first set the configuration options mentioned here: https://github.com/0xFireball/PenguinUpload#setup-instructions-from-source

For setup you will want to enable registration and create your account, then stop the server, add your username to the admins list, and disable registration if you like.
